name: register
description: The purpose of the library is to have a standard way of generating an object, an Id, that can be used in any of a variety of casing contexts.
version: 1.0.1
homepage: https://github.com/ScerIO/packages.dart/tree/master/packages/register

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  quiver: ^3.1.0
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
