name: extension
description: Package including lot helpers for easy developing on dart language
version: 0.5.0
homepage: https://github.com/ScerIO/packages.dart/tree/master/packages/extension

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  test: ^1.21.1
